apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rasterexport
spec:
  selector:
    app: {{ .Release.Name }}-rasterexport
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
